services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    environment:
      - NODE_ENV=development

  client:
    build: ./client
    ports:
      - "1234:1234"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - server
